<?php
/**
 * Custom walker for the primary menu.
 */

class Wynim_Nav_Walker extends Walker_Nav_Menu {
	public function start_lvl(&$output, $depth = 0, $args = null): void {
		parent::start_lvl($output, $depth, $args); // TODO: Change the autogenerated stub
	}

	public function end_lvl(&$output, $depth = 0, $args = null): void {
		parent::end_lvl($output, $depth, $args); // TODO: Change the autogenerated stub
	}
}
